#define IDM_MAINMENU 200

#define IDM_FILE_NEW 201
#define IDM_FILE_OPEN 203
#define IDM_FILE_SAVE 204
#define IDM_FILE_SAVEAS 205
#define IDM_FILE_EXIT 206

#define IDM_EDIT_UNDO 207
#define IDM_EDIT_REDO 208
#define IDM_EDIT_MODE_WORLDEDIT 209
#define IDM_EDIT_MODE_LIVEWORLDEDIT 210
#define IDM_EDIT_MODE_PLAYTEST 211

#define IDM_VIEW_TOOLBOX 225
#define IDM_VIEW_TILELIST 226
#define IDM_VIEW_GRID 227
#define IDM_VIEW_LAYERALL 228
#define IDM_VIEW_LAYERSTACKED 229
#define IDM_VIEW_LAYERSINGLE 230
#define IDM_VIEW_LAYERTRANS	231
#define IDM_VIEW_TRIGGERS 232

#define IDM_MAP_ADDTILESET 250
#define IDM_MAP_ADDPLAYER 251
#define IDM_MAP_ADDENEMIES 252
#define IDM_MAP_ADDBACKGROUND 253
#define IDM_MAP_SHOWENEMIES 254
#define IDM_MAP_SHOWTILESET 255
#define IDM_MAP_ADDMUSIC 256

#define IDM_TOOL_PENCIL 300
#define IDM_TOOL_BOX 301
#define IDM_TOOL_ENEMY 302
#define IDM_TOOL_PLAYERSPAWNPOINT 303
#define IDM_TOOL_LUATRIGGER 304

#define ICON_SELECT 350
#define ICON_DRAW 351
#define ICON_ERASE 352

#define IDT_SELECT 400
#define IDT_DRAW 401
#define IDT_ERASE 402

#define IDD_NEW 500
#define IDD_NEW_EDITHEIGHT 501
#define IDD_NEW_EDITWIDTH 502
#define IDD_NEW_EDITLAYERS 503
#define IDD_NEW_EDITACTIVE 504

#define IDC_STATIC 601
#define IDC_NEWCREATE 602
